tools:
  - name: token
    functions:
      - name: get_price
        module: tools.token.logic
        function: get_price
        schema_module: tools.token.schema
        schema_class: GetTokenParams
        response_schema_module: tools.token.schema
        response_schema_class: GetPriceResponse
        usage_hint: "Extract project socials using CA address"

      - name: get_symbol_price
        module: tools.market.logic
        function: get_symbol_price
        schema_module: tools.market.schema
        schema_class: GetSymbolPriceParams
        response_schema_module: tools.market.schema
        response_schema_class: GetSymbolPriceResponse
        usage_hint: "Extract project socials using symbol, Use the current method when the user queries the price by the token name."

      - name: get_tokens
        module: tools.token.logic
        function: get_tokens
        schema_module: tools.token.schema
        schema_class: GetWalletTokensParams
        response_schema_module: tools.token.schema
        response_schema_class: GetTokensResponse
        usage_hint: "Extract project socials using CA address"


      - name: get_native_balance
        module: tools.token.logic
        function: get_native_balance
        schema_module: tools.token.schema
        schema_class: GetWalletTokensParams
        response_schema_module: tools.token.schema
        response_schema_class: GetNativeBalanceResponse
        usage_hint: "Extract project socials using CA address"

      - name: get_token_metadata
        module: tools.token.logic
        function: get_token_metadata
        schema_module: tools.token.schema
        schema_class: GetTokenParams
        response_schema_module: tools.token.schema
        response_schema_class: GetTokenMetadataResponse
        usage_hint: "Extract project socials using CA address"

      - name: get_token_ownership
        module: tools.token.logic
        function: get_token_ownership
        schema_module: tools.token.schema
        schema_class: GetTokenParams
        response_schema_module: tools.token.schema
        response_schema_class: GetTokenOwnershipResponse
        usage_hint: "Extract project socials using CA address"

      - name: get_holder_summary
        module: tools.token.logic
        function: get_holder_summary
        schema_module: tools.token.schema
        schema_class: GetTokenParams
        response_schema_module: tools.token.schema
        response_schema_class: GetHolderSummaryResponse
        usage_hint: "Extract project socials using CA address"

      - name: get_token_pair_stats
        module: tools.token.logic
        function: get_token_pair_stats
        schema_module: tools.token.schema
        schema_class: GetTokenParams
        response_schema_module: tools.token.schema
        response_schema_class: GetTokenPairStatsResponse
        usage_hint: "Extract project socials using CA address"

      - name: get_token_socials
        module: tools.token.logic
        function: get_token_socials
        schema_module: tools.token.schema
        schema_class: GetTokenParams
        response_schema_module: tools.token.schema
        response_schema_class: GetTokenSocialsResponse
        usage_hint: "Extract project socials using CA address"

      - name: get_my_wallet_address
        module: tools.token.logic
        function: get_my_wallet_address
        schema_module: tools.token.schema
#        schema_class: GetMyWalletAddressParams
        response_schema_module: tools.token.schema
        response_schema_class: GetMyWalletAddressResponse

  - name: twitter
    functions:
      - name: get_user_handle_info
        module: tools.twitter.logic
        function: get_user_handle_info
        schema_module: tools.twitter.schema
        schema_class: GetUserHandleInfoParams
        response_schema_module: tools.twitter.schema
        response_schema_class: GetUserInfoResponse

      - name: get_user_id_info
        module: tools.twitter.logic
        function: get_user_id_info
        schema_module: tools.twitter.schema
        schema_class: GetUserIDInfoParams
        response_schema_module: tools.twitter.schema
        response_schema_class: GetUserInfoResponse

      - name: get_user_tweets
        module: tools.twitter.logic
        function: get_user_tweets
        schema_module: tools.twitter.schema
        schema_class: GetUserTweetsParams
        response_schema_module: tools.twitter.schema
        response_schema_class: GetTweetsResponse

      - name: get_twitter_check_follow
        module: tools.twitter.logic
        function: get_twitter_check_follow
        schema_module: tools.twitter.schema
        schema_class: GetTwitterCheckFollowParams
        response_schema_module: tools.twitter.schema
        response_schema_class: GetTwitterCheckFollowResponse

  - name: market
    functions:
      - name: get_symbol_kline_data
        module: tools.market.logic
        function: get_symbol_kline_data
        schema_module: tools.market.schema
        schema_class: GetSymbolKlineDataParams
        response_schema_module: tools.market.schema
        response_schema_class: GetSymbolKlineDataResponse
        usage_hint: "Extract project socials using symbol"

      - name: get_symbol_fetch_news
        module: tools.market.logic
        function: get_symbol_fetch_news
        schema_module: tools.market.schema
        schema_class: GetSymbolFetchNewsParams
        response_schema_module: tools.market.schema
        response_schema_class: GetSymbolFetchNewsResponse
        usage_hint: "Extract project socials using symbol"

